# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: blukasho <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/04 12:08:45 by blukasho          #+#    #+#              #
#    Updated: 2019/07/04 15:44:00 by blukasho         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = test_termios.c

FLAGS = -Wall -Wextra -Werror -g3 -fsanitize=address -I includes

all:
	gcc $(FLAGS) $(SRCS)
